name: run-tests

on:
  push:
  schedule:
    - cron: "0 0 * * 0"

jobs:
  php82-phpunit10:

    name: PHP${{ matrix.php }} TB${{ matrix.testbench }} ${{ matrix.os-title }} ${{ matrix.dependency-prefer-title }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        php: [8.2]
        testbench: [^8.0]
        phpunit: ["^10.1.0"]
        dependency-prefer: [prefer-stable, prefer-lowest]
        phpunit-config-file: [phpunit.xml.dist]
        include:
          - os: ubuntu-latest
            os-title: ubuntu
          - os: macos-latest
            os-title: macos
          - os: windows-latest
            os-title: win
          - dependency-prefer: prefer-stable
            dependency-prefer-title: stable
          - dependency-prefer: prefer-lowest
            dependency-prefer-title: lowest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: fileinfo, mb_string
          coverage: none

      - name: Install dependencies (composer)
        run: |
          composer require "orchestra/testbench:${{ matrix.testbench }}" "phpunit/phpunit:${{ matrix.phpunit }}" --dev --no-interaction --no-update
          composer update --${{ matrix.dependency-prefer }} --prefer-dist --no-interaction

      - name: Execute tests
        run: vendor/bin/phpunit --configuration=${{ matrix.phpunit-config-file }} --no-coverage --stop-on-error --stop-on-failure --exclude-group=ignore

  php82-phpunit9:

    name: PHP${{ matrix.php }} TB${{ matrix.testbench }} ${{ matrix.os-title }} ${{ matrix.dependency-prefer-title }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        php: [8.2]
        testbench: [^6.22, ^7.0]
        phpunit: ["^9.6"]
        dependency-prefer: [prefer-stable, prefer-lowest]
        phpunit-config-file: [phpunit.up-to-9.xml.dist]
        include:
          - os: ubuntu-latest
            os-title: ubuntu
          - os: macos-latest
            os-title: macos
          - os: windows-latest
            os-title: win
          - dependency-prefer: prefer-stable
            dependency-prefer-title: stable
          - dependency-prefer: prefer-lowest
            dependency-prefer-title: lowest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: fileinfo, mb_string
          coverage: none

      - name: Install dependencies (composer)
        run: |
          composer require "orchestra/testbench:${{ matrix.testbench }}" "phpunit/phpunit:${{ matrix.phpunit }}" --dev --no-interaction --no-update
          composer update --${{ matrix.dependency-prefer }} --prefer-dist --no-interaction

      - name: Execute tests
        run: vendor/bin/phpunit --configuration=${{ matrix.phpunit-config-file }} --no-coverage --stop-on-error --stop-on-failure --exclude-group=ignore

  php81:

    name: PHP${{ matrix.php }} TB${{ matrix.testbench }} ${{ matrix.os-title }} ${{ matrix.dependency-prefer-title }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        php: [8.1]
        testbench: [^6.22, ^7.0, ^8.0]
        phpunit: ["^9.6"]
        dependency-prefer: [prefer-stable, prefer-lowest]
        phpunit-config-file: [phpunit.up-to-9.xml.dist]
        include:
          - os: ubuntu-latest
            os-title: ubuntu
          - os: macos-latest
            os-title: macos
          - os: windows-latest
            os-title: win
          - dependency-prefer: prefer-stable
            dependency-prefer-title: stable
          - dependency-prefer: prefer-lowest
            dependency-prefer-title: lowest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: fileinfo, mb_string
          coverage: none

      - name: Install dependencies (composer)
        run: |
          composer require "orchestra/testbench:${{ matrix.testbench }}" "phpunit/phpunit:${{ matrix.phpunit }}" --dev --no-interaction --no-update
          composer update --${{ matrix.dependency-prefer }} --prefer-dist --no-interaction

      - name: Execute tests
        run: vendor/bin/phpunit --configuration=${{ matrix.phpunit-config-file }} --no-coverage --stop-on-error --stop-on-failure --exclude-group=ignore

  php80:

    name: PHP${{ matrix.php }} TB${{ matrix.testbench }} ${{ matrix.os-title }} ${{ matrix.dependency-prefer-title }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        php: ["8.0"]
        testbench: [^6.0, ^5.0]
        phpunit: ["^9.3"]
        dependency-prefer: [prefer-stable, prefer-lowest]
        phpunit-config-file: [phpunit.up-to-9.xml.dist]
        include:
          - os: ubuntu-latest
            os-title: ubuntu
          - os: macos-latest
            os-title: macos
          - os: windows-latest
            os-title: win
          - dependency-prefer: prefer-stable
            dependency-prefer-title: stable
          - dependency-prefer: prefer-lowest
            dependency-prefer-title: lowest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: fileinfo, mb_string
          coverage: none

      - name: Install dependencies (composer)
        run: |
          composer require "orchestra/testbench:${{ matrix.testbench }}" "phpunit/phpunit:${{ matrix.phpunit }}" --dev --no-interaction --no-update
          composer update --${{ matrix.dependency-prefer }} --prefer-dist --no-interaction

      - name: Execute tests
        run: vendor/bin/phpunit --configuration=${{ matrix.phpunit-config-file }} --no-coverage --stop-on-error --stop-on-failure --exclude-group=ignore
