name: run-tests

on:
  push:
  schedule:
    - cron: "0 0 * * 0"

jobs:
  php-81:

    name: ${{ matrix.os }} - PHP ${{ matrix.php }} - TestBench ${{ matrix.testbench }} - ${{ matrix.dependency-prefer }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        php: [8.1]
        testbench: [^6.22]
        dependency-prefer: [prefer-stable, prefer-lowest]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: fileinfo, mb_string
          coverage: none

      # find out composer's cache directory on the current os - for the "Cache dependencies (composer)" step below
      - name: Determine composer's cache directory
        id: composer-cache
        run: |
          echo "::set-output name=dir::$(composer config cache-files-dir)"

      - name: Cache dependencies (composer)
        uses: actions/cache@v2
        with:
          path: ~/.composer/cache/files
          key: php-${{ matrix.php }}-testbench-${{ matrix.testbench }}-os-${{ matrix.os }}-dependency-prefer-${{ matrix.dependency-prefer }}-composer-${{ hashFiles('composer.json') }}

      - name: Install dependencies
        run: |
          composer require "orchestra/testbench:${{ matrix.testbench }}" --dev --no-interaction --no-update
          composer update --${{ matrix.dependency-prefer }} --prefer-dist --no-interaction

      - name: Execute tests
        run: vendor/bin/phpunit --exclude-group=ignore

  php-80:

    name: ${{ matrix.os }} - PHP ${{ matrix.php }} - TestBench ${{ matrix.testbench }} - ${{ matrix.dependency-prefer }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        php: ["8.0"]
        testbench: [^6.0, ^5.0]
        dependency-prefer: [prefer-stable, prefer-lowest]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: fileinfo, mb_string
          coverage: none

      # find out composer's cache directory on the current os - for the "Cache dependencies (composer)" step below
      - name: Determine composer's cache directory
        id: composer-cache
        run: |
          echo "::set-output name=dir::$(composer config cache-files-dir)"

      - name: Cache dependencies (composer)
        uses: actions/cache@v2
        with:
          path: ~/.composer/cache/files
          key: php-${{ matrix.php }}-testbench-${{ matrix.testbench }}-os-${{ matrix.os }}-dependency-prefer-${{ matrix.dependency-prefer }}-composer-${{ hashFiles('composer.json') }}

      - name: Install dependencies
        run: |
          composer require "orchestra/testbench:${{ matrix.testbench }}" --dev --no-interaction --no-update
          composer update --${{ matrix.dependency-prefer }} --prefer-dist --no-interaction

      - name: Execute tests
        run: vendor/bin/phpunit --exclude-group=ignore
