name: Run tests

on: [push, pull_request]

jobs:
  test:
    name: ${{ matrix.os }} - PHP ${{ matrix.php }} - Laravel ${{ matrix.laravel }} - ${{ matrix.dependency-prefer }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]
        php: ["8.0"]
        laravel: [8.*, 7.*]
        dependency-prefer: [prefer-stable, prefer-lowest]
        include:
          - testbench: 6.*
            laravel: 8.*
          - testbench: 5.*
            laravel: 7.*
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Cache dependencies (composer)
        uses: actions/cache@v2
        with:
          path: ~/.composer/cache/files
          key: dependencies-laravel-${{ matrix.laravel }}-php-${{ matrix.php }}-composer-${{ hashFiles('composer.json') }}

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: mb_string
          coverage: none

      - name: Install dependencies
        run: |
          composer require "orchestra/testbench:${{ matrix.testbench }}" --no-interaction --no-update
          composer update --${{ matrix.dependency-prefer }} --prefer-dist --no-interaction --no-suggest

      - name: Execute tests
        run: vendor/bin/phpunit --exclude-group=ignore
